name: mobile
description: Ride booking demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  http: ^1.2.2
  flutter_map: ^8.2.2
  dio: ^5.7.0
  latlong2: ^0.9.1
  mqtt_client: ^10.11.1
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/config.env
    - assets/car.png
